apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-spring-boot
  labels:
    app: automation-spring-boot
spec:
  selector:
    matchLabels:
      app: automation-spring-boot
  replicas: 1
  template:
    metadata:
      labels:
        app: automation-spring-boot
    spec:
      containers:
      - name: automation-spring-boot
        image: rhhdevacr.azurecr.io/jioent/health/automation-spring-boot:sit-20230802.1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 256Mi
            cpu: "250m"
          requests:
            memory: 128Mi
            cpu: "80m"
      imagePullSecrets:
      - name: acr-repo
