apiVersion: v1
kind: Service
metadata:
  name: automation-spring-boot
spec:
  selector:
    app: automation-spring-boot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  type: ClusterIP
