---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /rfh-kafka-publisher(/|$)(.*)
            backend:
              service:
                name: rfh-kafka-publisher
                port:
                  number: 80
          - pathType: Prefix
            path: /data-persistence-service(/|$)(.*)
            backend:
              service:
                name: data-persistence-service
                port:
                  number: 80
          - pathType: Prefix
            path: /data-storage-service(/|$)(.*)
            backend:
              service:
                name: data-storage-service
                port:
                  number: 80
          - pathType: Prefix
            path: /keycloak(/|$)(.*)
            backend:
              service:
                name: keycloak
                port:
                  number: 80
          - pathType: Prefix
            path: /bifrost-outbound-integration-service(/|$)(.*)
            backend:
              service:
                name: bifrost-outbound-integration-service
                port:
                  number: 80
          - pathType: Prefix
            path: /bifrost-inbound-integration-service(/|$)(.*)
            backend:
              service:
                name: bifrost-inbound-integration-service
                port:
                  number: 80
          - pathType: Prefix
            path: /bifrost-partner-registry-service(/|$)(.*)
            backend:
              service:
                name: bifrost-partner-registry
                port:
                  number: 80
          - pathType: Prefix
            path: /encryption(/|$)(.*)
            backend:
              service:
                name: encryption
                port:
                  number: 80
          - pathType: Prefix
            path: /integration(/|$)(.*)
            backend:
              service:
                name: bifrost-encryption-service
                port:
                  number: 80
          - pathType: Prefix
            path: /developer-portal(/|$)(.*)
            backend:
              service:
                name: developer-portal
                port:
                  number: 80
          - pathType: Prefix
            path: /data-transformation-service(/|$)(.*)
            backend:
              service:
                name: data-transformation-service
                port:
                  number: 80
          - pathType: Prefix
            path: /bifrost-router-service(/|$)(.*)
            backend:
              service:
                name: bifrost-router-service
                port:
                  number: 80
          - pathType: Prefix
            path: /webapp-integration(/|$)(.*)
            backend:
              service:
                name: webapp-integration
                port:
                  number: 80
          - pathType: Prefix
            path: /bifrost-protocol-mapper-service(/|$)(.*)
            backend:
              service:
                name: bifrost-protocol-mapper-service
                port:
                  number: 80
          - pathType: Prefix
            path: /bifrost-onboarding-template-engine(/|$)(.*)
            backend:
              service:
                name: bifrost-onboarding-template-engine
                port:
                  number: 80
          - pathType: Prefix
            path: /data-storage-controller-service(/|$)(.*)
            backend:
              service:
                name: data-storage-controller-service
                port:
                  number: 80
          - pathType: Prefix
            path: /bifrost-azure-infra-interface(/|$)(.*)
            backend:
              service:
                name: bifrost-azure-infra-interface
                port:
                  number: 80
          - pathType: Prefix
            path: /payment-service(/|$)(.*)
            backend:
              service:
                name: payment-service
                port:
                  number: 80

          - pathType: Prefix
            path: /data-storage-sql-service(/|$)(.*)
            backend:
              service:
                name: data-storage-sql-service
                port:
                  number: 80
          - pathType: Prefix
            path: /ingestion-controller-service(/|$)(.*)
            backend:
              service:
                name: ingestion-controller-service
                port:
                  number: 80
          - pathType: Prefix
            path: /data-storage-nosql-service(/|$)(.*)
            backend:
              service:
                name: data-storage-nosql-service
                port:
                  number: 80
          - pathType: Prefix
            path: /bifrost-background-jobs-service(/|$)(.*)
            backend:
              service:
                name: bifrost-background-jobs-service
                port:
                  number: 80
          - pathType: Prefix
            path: /bifrost-background-jobs-dashboard(/|$)(.*)
            backend:
              service:
                name: bifrost-background-jobs-dashboard
                port:
                  number: 80
          - pathType: Prefix
            path: /bifrost-catalogue-service(/|$)(.*)
            backend:
              service:
                name: bifrost-catalogue-service
                port:
                  number: 80
          - pathType: Prefix
            path: /bifrost-ingestion-controller-service(/|$)(.*)
            backend:
              service:
                name: bifrost-ingestion-controller-service
                port:
                  number: 80
          - pathType: Prefix
            path: /bifrost-scheduler-service(/|$)(.*)
            backend:
              service:
                name: bifrost-scheduler-service
                port:
                  number: 80
          - pathType: Prefix
            path: /bifrost-scheduler-service-dashboard(/|$)(.*)
            backend:
              service:
                name: bifrost-scheduler-service
                port:
                  number: 8081
          - pathType: Prefix
            path: /dashboard(/|$)(.*)
            backend:
              service:
                name: bifrost-scheduler-service
                port:
                  number: 8081
          - pathType: Prefix
            path: /listing-service(/|$)(.*)
            backend:
              service:
                name: listing-service
                port:
                  number: 80
          - pathType: Prefix
            path: /feedback-service(/|$)(.*)
            backend:
              service:
                name: feedback-service
                port:
                  number: 80
          - pathType: Prefix
            path: /onboard-corporate(/|$)(.*)
            backend:
              service:
                name: corporate-onboarding-service
                port:
                  number: 8080
          - pathType: Prefix
            path: /condition-management-service(/|$)(.*)
            backend:
              service:
                name: condition-management-service
                port:
                  number: 8080
          - pathType: Prefix
            path: /nutrition-tracker-service(/|$)(.*)
            backend:
              service:
                name: nutrition-tracker-service
                port:
                  number: 8080

          - pathType: Prefix
            path: /program-builder-service(/|$)(.*)
            backend:
              service:
                name: program-builder-service
                port:
                  number: 8080

          - pathType: Prefix
            path: /authenticate-corporate(/|$)(.*)
            backend:
              service:
                name: corporate-authentication-service
                port:
                  number: 8080
          - pathType: Prefix
            path: /corporate-onboard-webapp(/|$)(.*)
            backend:
              service:
                name: corporate-onboarding-webapp-service
                port:
                  number: 5000
          - pathType: Prefix
            path: /associate-tenant(/|$)(.*)
            backend:
              service:
                name: association-tenant-service
                port:
                  number: 8080
          - pathType: Prefix
            path: /entity-association(/|$)(.*)
            backend:
              service:
                name: entity-association-service
                port:
                  number: 8080
          - pathType: Prefix
            path: /onboarding-service(/|$)(.*)
            backend:
              service:
                name: onboarding-service
                port:
                  number: 80
          - pathType: Prefix
            path: /bifrost-encryption-service(/|$)(.*)
            backend:
              service:
                name: bifrost-encryption-service
                port:
                  number: 80
          - pathType: Prefix
            path: /webapp-partner-onboarding(/|$)(.*)
            backend:
              service:
                name: webapp-partner-onboarding
                port:
                  number: 80
          - pathType: Prefix
            path: /rule-engine-service(/|$)(.*)
            backend:
              service:
                name: rule-engine-service
                port:
                  number: 80
          - pathType: Prefix
            path: /corporate-service(/|$)(.*)
            backend:
              service:
                name: pme-service
                port:
                  number: 80
          - pathType: Prefix
            path: /corporate-user-onboarding-service(/|$)(.*)
            backend:
              service:
                name: corporate-user-onboarding-service
                port:
                  number: 80
          - pathType: Prefix
            path: /debezium(/|$)(.*)
            backend:
              service:
                name: debezium-consumertech
                port:
                  number: 80
          - pathType: Prefix
            path: /bifrost-database-to-json-service(/|$)(.*)
            backend:
              service:
                name: bifrost-database-to-json-service
                port:
                  number: 80
          - pathType: Prefix
            path: /test-onboarding-service(/|$)(.*)
            backend:
              service:
                name: test-onboarding-service
                port:
                  number: 80
          - pathType: Prefix
            path: /package-onboarding-service(/|$)(.*)
            backend:
              service:
                name: package-onboarding-service
                port:
                  number: 80
          - pathType: Prefix
            path: /bifrost-delta-calculation-service(/|$)(.*)
            backend:
              service:
                name: package-onboarding-service
                port:
                  number: 80
          - pathType: Prefix
            path: /condition-parameter-tracking-service(/|$)(.*)
            backend:
              service:
                name: condition-parameter-tracking-service
                port:
                  number: 8080
          - pathType: Prefix
            path: /provider-portal-service(/|$)(.*)
            backend:
              service:
                name: provider-portal-service
                port:
                  number: 80
          - pathType: Prefix
            path: /legacy-provider-migration-service(/|$)(.*)
            backend:
              service:
                name: legacy-provider-migration-service
                port:
                  number: 80